name: blood_system
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  uuid: ^4.3.3
  syncfusion_flutter_datepicker: ^30.1.40
  intl: ^0.20.2
  # flutter_local_notifications: ^12.0.4
  google_sign_in: ^6.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.2

dev_dependencies:
  google_fonts: ^6.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#D7263D" # Background color
  image: "assets/images/splash_logo.png" # Your splash image

  # Optional configurations
  color_dark: "#D7263D" # Dark mode background
  image_dark: "assets/images/splash_logo.png" # Dark mode image

  android_12:
    image: "assets/images/splash_logo.png"
    color: "#D7263D"

  # Platform specific settings
  android: true
  ios: true
  web: false
